spring:
  config:
    import: optional:file:../../.env[.properties]
  application:
    name: bms-api
  datasource:
    url: ${BMS_DB_URL}
    username: ${BMS_DB_USERNAME}
    password: ${BMS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
